### ISSUE TITLE
Vue components 정리

### ISSUE THREAD

**Issue by jinjaeCHAE** [rootsj/FinPic#2]
**1페이지(메인 페이지)**
핀픽로고 : 클릭 시, 메인페이지로 이동
검색창 : 검색 결과로 이동
로그인 : 로그인 페이지로 이동
이미지 클릭(무한로딩, 트렌트 순으로 정렬) : 이미지가 게시된 페이지로 이동

 **2페이지(메인 페이지)**
업로드 : 클릭시, 업로드로 이등(로그인 되어 있는 상태에서)
Mypage : 마이 페이지로 이동
로그아웃 : 로그아웃 후, 메인페이지로 이동

**3페이지(메인 페이지)**
검색명 및 검색 결과 수 : 검색명을 명시하고, 그 검색명에 따른 결과 수를 보여줌

**5페이지(로그인 페이지)**
로그인 : 아이디, 비밀번호를 받아 로그인, 후에 로그인 된 상태로 메인페이지 이동
가입하기 : 가업하기 페이지로 넘어감

**6페이지(가입하기 페이지)**
sign up : 이메일, 닉네임, 비밀번호, 비밀번호 검증 총 4개의 값을 받고 사인업 버튼 클릭시 메인페이지 이동, 이메일 || 닉네임 중복되면 sign up 비활성화

**7페이지(업로드)**
이미지 업로드 : 클릭하면 이미지 가져오기
게시하기 : 태그입력 받고 앞선 업로드된 데이터를 포함해 게시, 게시하기 클릭 후 게시된 게시물로 이동

**8페이지(마이페이지)**
프로필 이미지, 이름 , 설명 : 기존 입력되어 있는 것 창에 보여줌
favorite : favorite 모아논 것 보여주는 것
MyPage 수정 : 클릭하면 MyPage 수정으로 들어감
이미지 클릭 : 그 이미지를 게시한 게시글로 들어감
follower : 팔로워 수를 보여줌, 클릭 시 자신을 팔로워한 유저 명단 나옴
(확장)검색 :  내가 올린 게시글 중에 검색 가능

**9페이지(Favorite)**
이미지 클릭 : 그 이미지를 게시한 게시글로 들어감(마이페이지의 이미지 클릭과는 다름)
(확장)검색 :  내가 올린 게시글 중에 검색 가능

**10페이지(개인정보 수정)**
Save(개인정보 수정) : 닉네임, 이메일, 사용자 설명 값을 받고, save 클릭시 마이페이지로 이동
Save(SNS address) : 각각의 SNS 주소값을 받고, save 클릭시 마이페이지로 이동
계정 삭제 : 클릭시 계정 삭제되고 메인페이지로 이동

**11페이지(다른 사람 게시물)**
follow : 이 게시글을 올린 유저를 follow함, 그 유저는 follower 증가
like : 좋아요 선택, 게시글은 좋아요 수 늘어남
Favotrite : 클릭시 Favorite 새로 등록
Download : 다운로드하게 함
Copy link : 링크 복사해줌
조회수 : 이 글의 like 수를 보여줌

**Comment by byungs2** [comment]
정리 해놨어 Project에

**Comment by byungs2** [comment]
확인하고 수정한 담 Issue close 해주셈

**Comment by jinjaeCHAE** [comment]
이거 전체 확인용이여
