### ISSUE TITLE
Vue.dev1.01 update issue

### ISSUE THREAD

**Issue by byungs2** [rootsj/FinPic#22]
Vue.dev1.01
I did merge my local Vue project into Vue.dev1.01 directly without any pull request.

Update History
    1. like button fix
    2. report button fix
    3. my page user view fix

plz check it by yourself and leave your comment

**Comment by rootsj** [comment]
3. my page user view fix -> view 가 아니라 image임 참고

**Comment by pure-teatree** [comment]
확인!
