### ISSUE TITLE
swagger 업데이트 및 pull requests 주의점

### ISSUE THREAD

**Issue by rootsj** [rootsj/FinPic#9]
1. 현재 dev1.0에 follow 및 swagger 업데이트 완료됨
    원래는 follow 머지 후에 swagger도 pull request 요청하려고 했으나
   swagger도 같이 머지가됨

그 이유) swagger를 적용하고
git으로 push를 하였고 그 후 새로운 full request를 요청하려고 했으나
full request(머지 전) 가 아직 수락되지 않은 상태였음

그 상태를 보고 내가 그냥 자가 수락해서 머지하고 새로운 리퀘스트 하려고 했으나
실시간으로 remote가 업데이트가되어서 swagger적용 버전까지 dev1.0으로 머지가 됨...!

다들 앞으로 full requests요청할때 주의하도록! 아니면 새로운 branch로 작업하도록

2. swagger업데이트 완료되었고 swagger 컨트롤러 설명은 각자 추가하도록!

3. readme파일에 pom.xml 내용 업데이트 했고(swagger내용)

4. application.properties 내용 보니까 진재가 올린 것이 인코딩이 깨져있었음(주석부문)
다들 utf-8인지 다시한번 확인하도록! 
application.properties 깨진부분은 바꿔서 다시 리퀘스트 할 수 있도록! ㅋㅋ

다들 1,2,3,4번 확인하고 코멘트를 다십시오~

**Comment by byungs2** [comment]
확인 완료~ 난 UTF-8로 되어있음
